[general]
import = [
  "/home/filip/.config/alacritty/themes/themes/gruvbox_dark.toml",
  "/home/filip/.config/alacritty/themes/themes/filipwe-light.toml",
]

live_config_reload = true

[font]
size = 12 # 16 on Mac

[font.bold]
family = "Roboto Mono for Powerline"

[font.bold_italic]
family = "Roboto Mono Light for Powerline"
style = "Bold Italic"

[font.italic]
family = "Roboto Mono Light for Powerline"
style = "Italic"

[font.normal]
family = "Roboto Mono Light for Powerline"

[[hints.enabled]]
command = "firefox"
post_processing = true
regex = "(mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\" {-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true
mods = "Control"

[window]
# startup_mode = "Fullscreen" # On Mac
decorations_theme_variant = "Dark"

[bell]
duration = 300
animation = "EaseOutCirc"
color = "#bfbfbf"
